# this file is for setting up app configuration

spring.application.name=myapp

# instead of listening to default port(8080) , listen to this port
server.port= 8080

# configure properties that will be  used  in the java app
#database.url = example.com
#database.username = yahya
#database.password = 1234

## in java app, this makes var databaseUrl = database.url , so that u can change config without changing java code
# @Value("${database.url}")
# private String databaseUrl;


info.app.name = My App
info.app.description = fun app
info.app.version = 1.0

management.endpoints.web.exposure.include= health,info
# allows access to the health and info endpoints


management.info.env.enabled= true
# decides whether you can get information from the info endpoint
