spring.application.name=restcruddemo


                    # connect the java app to the database #

spring.datasource.url= jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username= springstudent
spring.datasource.password= springstudent



                    # Spring Data REST properties  #

spring.data.rest.base-path= /api

# page size is the number of entities that would be shown at once
spring.data.rest.default-page-size = 20 


springdoc.show-actuator=false
springdoc.data-rest.enabled=false


                            # OpenAPI & Swagger #

# change the swagger ui path
springdoc.swagger-ui.path=/my-ui.html

# change the API documentation path (no need for v3)
springdoc.api-docs.path=/my-api-docs