spring.application.name=restcruddemo


                    # connect the java app to the database #

spring.datasource.url= jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username= springstudent
spring.datasource.password= springstudent



                    # Spring Data REST properties  #

spring.data.rest.base-path= /api

# page size is the number of entities that would be shown at once
spring.data.rest.default-page-size = 20 


